// Generated by typings
// Source: app/custom_typings/objloader/index.d.ts
declare namespace THREE
{
    export class OBJLoader
    {
        constructor( manager?: THREE.LoadingManager );

        load( url: string,
              onLoad: ( model: any ) => void,
              onProgress?: ( request: ProgressEvent ) => void,
              onError?: ( event: ErrorEvent ) => void ): void;

        parse( data: string ): boolean;
    }
}
